**Create Arrays**

* Create a 1D array of numbers from 0 to 9.
* Create a 2D array (3x3) filled with random numbers.
* Create an array of 10 ones and an array of 10 zeros.

In [1]:
import numpy as np

In [2]:
# 1D array oof number froom 0 to 9
v=np.arange(1,10)
print(v)

# 2D array (3x3) filled with random numbers
m=np.random.randint(100,size=(3,3))
print(m)

#an array of 10 ones and an array of 10 zeros.
ones=np.ones(10)
print(ones)
zeros=np.zeros(10)
print(zeros)

[1 2 3 4 5 6 7 8 9]
[[ 3 54 35]
 [ 4 34 88]
 [ 5 99 64]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Basic Operations**
* Add, subtract, multiply, and divide two NumPy arrays element-wise.
* Find the mean, median, standard deviation, and variance of an array.
* Sort an array in ascending and descending order.

In [3]:
# Add, subtract, multiply, and divide two NumPy arrays element-wise.
v=np.array([1,2,3,8,10])
m=np.array([3,9,5,7,2])
a=np.add(v,m)
print(np.add(v,m))
print(np.subtract(v,m))
print(np.multiply(v,m))
print(np.divide(v,m))


[ 4 11  8 15 12]
[-2 -7 -2  1  8]
[ 3 18 15 56 20]
[0.33333333 0.22222222 0.6        1.14285714 5.        ]


In [4]:
# Find the mean, median, standard deviation, and variance of an array.
print(v.mean())
print(np.median(m))

4.8
5.0


In [5]:
# Sort an array in ascending and descending order.
print(np.sort(v))
print(np.sort(v)[::-1])

[ 1  2  3  8 10]
[10  8  3  2  1]


**Indexing & Slicing**

* Extract the first 5 elements from a given array.
* Get all even numbers from an array.
* Replace all values greater than 5 in an array with 0.

In [6]:
# Extract the first 5 elements from a given array.
v=np.random.randint(50,size=10)
print(v)
print(v[:5])
# Get all even numbers from an array.
print(v[v%2==0])
# Replace all values greater than 5 in an array with 0.
new_v=np.where(v>5,0,v)
print(new_v)


[22 20 24 36 38  8 39 33 27 32]
[22 20 24 36 38]
[22 20 24 36 38  8 32]
[0 0 0 0 0 0 0 0 0 0]


In [7]:
# Convert a 1D Array into a 2D Matrix of Shape (4,3)

v = np.arange(12)  
m = v.reshape(4, 3)

print(m)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# Replace Negative Values with 0

arr = np.random.randint(-10, 10, size=10)
arr[arr < 0] = 0  

print(arr)


[0 2 0 4 0 0 0 7 3 0]
