# Numpy stage 1

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(type(a))
a*b

<class 'numpy.ndarray'>


array([ 1,  4,  9, 16, 25])

* Create a array

In [3]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [4]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
np.full((3,5),10,dtype=int)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [6]:
np.arange(0,61,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60])

In [7]:
np.random.randint(0,10,(3,4))

array([[6, 5, 4, 5],
       [5, 2, 9, 8],
       [1, 5, 9, 0]])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**numpy array features**
* ndim
* shape
* size
* dtype


In [9]:
a = np.random.randint(10,size=10)
print(a)

[7 9 0 1 8 2 3 4 9 0]


In [10]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)

1
(10,)
int64
10


In [11]:
b= np.random.randint(10 ,size=(3,5))
print(b)

[[2 7 0 6 1]
 [9 7 9 5 4]
 [6 5 1 7 5]]


In [12]:
print(b.ndim)
print(b.shape)
print(b.dtype)
print(b.size)

2
(3, 5)
int64
15


**reshaping**

In [13]:
c=np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [14]:
b=c.reshape((3,3))


In [15]:
b.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Concatenation**

In [16]:
a=np.arange(1,5)
b=np.arange(5,9)

In [17]:
c=np.concatenate([a,b])
print(c)
#make 2d array
d=np.concatenate([[a,b]])
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
e=np.array([[2,4,5,6],
           [7,8,9,0]])

np.concatenate([e,d])

array([[2, 4, 5, 6],
       [7, 8, 9, 0],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.concatenate([e,d],axis=1)

array([[2, 4, 5, 6, 1, 2, 3, 4],
       [7, 8, 9, 0, 5, 6, 7, 8]])

**Splitting**

In [20]:
a= np.arange(16)
print(a)
np.split(a,[4,8,12])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [21]:
a=np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [22]:
b,c=np.vsplit(a,[2])
print(c)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [23]:
b,c=np.hsplit(a,[3])
print(b)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]
 [20 21 22]]


**Sorting**

In [24]:
a=np.random.randint(100,size=(10))
np.sort(a)

array([ 6, 17, 47, 57, 60, 77, 81, 85, 86, 90])

In [25]:
a=np.random.randint(100,size=(4,4))
np.sort(a,axis=0)
np.sort(a,axis=1)

array([[15, 65, 73, 89],
       [ 1,  5, 71, 75],
       [38, 54, 57, 86],
       [55, 61, 73, 86]])

**access value by index**

In [26]:
a=np.random.randint(100,size=9)
print(a)

[54 46 66 73 46 96  0 20 54]


In [27]:
a[0]
#update value
a[0]=12
a

array([12, 46, 66, 73, 46, 96,  0, 20, 54])

In [28]:
a=np.random.randint(100,size=(3,4))
a

array([[51, 39,  2, 55],
       [ 9,  4, 27, 59],
       [55, 92,  3, 52]])

In [29]:
a[1,2]
#update value
a[1,2]=10
a

array([[51, 39,  2, 55],
       [ 9,  4, 10, 59],
       [55, 92,  3, 52]])

**copy method**

In [30]:
m=np.random.randint(100,size=(5,5))
m

array([[96, 47, 67, 66, 58],
       [91, 97, 64, 60, 73],
       [78, 81, 70, 71, 30],
       [39, 78, 51, 38,  5],
       [ 4, 12, 32, 66, 88]])

In [31]:
m_new=m[:3,:3].copy() # copy() method allow to make change and do not efect the origin array!
m_new[1,1]=12
m_new

array([[96, 47, 67],
       [91, 12, 64],
       [78, 81, 70]])

**Fancy index**

In [32]:
v=np.arange(6,14)
v

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [33]:
i=np.array([4,3,7,5])
print(v[i])

[10  9 13 11]


* Fancy in 2d array

In [34]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
u=np.array([3,1])
v=np.array([1,2])
m[u,v]


array([13,  6])

In [36]:
m[0:,v]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

**conditions**

In [37]:
v=np.arange(5)

In [38]:
v[v>2]

array([3, 4])

In [39]:
v[v<=2]

array([0, 1, 2])

* Math

In [40]:
v**2

array([ 0,  1,  4,  9, 16])

In [41]:
v*10/5

array([0., 2., 4., 6., 8.])